language: java

jdk:
- openjdk11

addons:
  sonarcloud:
    organization: "gaia-app"

cache:
  directories:
    - $HOME/.m2

git:
  depth: false

stages:
  - name: test
  - name: deploy
    if: branch = master AND tag IS present

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      install: skip
      script:
      # fetching master refs when building other branches helps sonar computing PRs
      - git fetch origin +refs/heads/main:refs/remotes/origin/main
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report sonar:sonar
